# Generated by Django 2.2.3 on 2019-07-24 17:08

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerProfile',
            fields=[
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='owner_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('salon_name', models.CharField(max_length=20)),
                ('salon_address', models.CharField(max_length=255)),
                ('salon_city', models.CharField(max_length=255)),
                ('salon_state', models.CharField(max_length=2)),
                ('salon_zip', models.CharField(max_length=5)),
                ('salon_phone_number', models.CharField(max_length=10)),
                ('salon_description', models.TextField(max_length=2000)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('common.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
