# Generated by Django 2.2.3 on 2019-07-26 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owners_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerprofile',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='salon_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
