# Generated by Django 2.2.3 on 2019-07-24 17:19

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StylistProfile',
            fields=[
                ('stylist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='stylist_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(max_length=10)),
                ('years_experience', models.IntegerField(default=0)),
                ('licenses', models.FileField(blank=True, upload_to='uploads')),
                ('photo1', models.ImageField(blank=True, upload_to='uploads')),
                ('photo2', models.ImageField(blank=True, upload_to='uploads')),
                ('photo3', models.ImageField(blank=True, upload_to='uploads')),
                ('photo4', models.ImageField(blank=True, upload_to='uploads')),
                ('photo5', models.ImageField(blank=True, upload_to='uploads')),
                ('photo6', models.ImageField(blank=True, upload_to='uploads')),
                ('specializations', models.TextField(max_length=1000)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('common.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
